version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:alpine
    command:
      - redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"

